# These are supported funding model platforms

github:  [sourabhmishra-2003,chetnadixit,higharmour]
patreon: https://www.patreon.com/Higharmour
open_collective: # 
ko_fi: sourabh23
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: web development
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: [www.sourabh.42web.io,www.chetna.cf]
